project_id = "xqsbeirysuujnussnmfc"

[functions.health]
verify_jwt = false

[functions.db-test]
verify_jwt = false

[functions.proyectos]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.validar-codigo]
verify_jwt = false

[functions.registrar-estudiante]
verify_jwt = false
